version: '3.9'
services:
    php-fpm:
        build:
            context: ./deploy/runtime
            dockerfile: Dockerfile
        container_name: php-fpm_atieh
        environment:
            XDEBUG: "true"
            PHP_IDE_CONFIG: "serverName=my.local"
        working_dir: /var/www
        user: ${CURRENT_UID}
        volumes:
            - ./:/var/www
            - ./deploy/etc/php/local.ini:/usr/local/etc/php/conf.d/local.ini
            - ./deploy/init-database.sh:/docker-entrypoint.d/10-init-database.sh
        command: bash -c "/docker-entrypoint.d/10-init-database.sh && php-fpm"
        depends_on:
            mysql:
              condition: service_healthy
        networks:
            - my_service #if you're using networks between containers

    webserver:
        image: nginx:latest
        tty: true
        ports:
          - 80:80
        volumes:
          - ./:/var/www
          - ./public:/var/www/public
          - ./deploy/etc/nginx/conf.d/:/etc/nginx/conf.d/
        depends_on:
          - php-fpm
        networks:
          - my_service

    mysql:
        image: mariadb
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - './mysql_data:/var/lib/mysql'
            - './deploy/create-database.sh:/docker-entrypoint-initdb.d/10-create-database.sh'
        networks:
            - my_service
        healthcheck:
            test:
                - CMD
                - mysqladmin
                - ping
                - '-p${DB_PASSWORD}'
            interval: 10s
            retries: 4
            timeout: 5s


networks:
  my_service:
    external: true
